# Generated by Django 4.1.5 on 2023-03-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
