# Generated by Django 4.1.5 on 2023-03-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintapp', '0002_cport_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cport',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
