# Generated by Django 4.1.5 on 2023-02-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
