# Generated by Django 4.1.5 on 2023-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0002_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='is_fav',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
